version: "3.9" # Use a supported Compose version

services:
  api:
    build: ./api # Build the API image from the api/ Dockerfile
    volumes:
      - mongodb-data:/data/db # Mount MongoDB data volume
    environment:
      PORT: 3200
      BASE_URL: http://localhost:${PORT}
      SECRET_KEY: "hansome$$horses"
      MONGOURL: "mongodb://localhost:27017/velvet_vibes"
    depends_on:
      - mongodb
    ports:
      - "3200:3200" # Map API port to host port 8080
  client:
    build: ./client # Build the client image from the client/ Dockerfile
    environment:
      API_URL: http://api:8080 # Set environment variable for client to communicate with API
    ports:
      - "3000:3000" # Map client port to host port 3000
  mongodb:
    image: mongo:latest # Use the official MongoDB image
    volumes:
      - mongodb-data:/data/db # Create and persist MongoDB data volume
    ports:
      - "27017:27017" # Map MongoDB port to host port 27017

volumes:
  mongodb-data: # Define the shared MongoDB data volume
